<?php
$modulos = $this->modulos;
?>
<link type="text/css" href="<?php echo dirname($_SERVER['PHP_SELF']); ?>/css/cadastros.css" rel="stylesheet" rev="stylesheet"/>

<script type="text/javascript">
    $(document).ready(function() {
        $('#<?php Tab::tabIdEcho('pesquisa'); ?>').focus();
        
        $("#<?php Tab::tabIdEcho('pesquisa'); ?>").keyup(function(){
            var palavra = $(this).val();
            var input = $("#<?php Tab::tabIdEcho('listarAplicacaoInput'); ?>").val();
            
            if (palavra.length > 2) {
                $.post(
                    "<?php echo BASE_URL . '/clinica/aplicacao/listar'; ?>", 
                    {aplicacao: palavra, input: input},
                    function(data, status){
                        if(status == 'success' && $.trim(data) != 'naopassou') {
                            $("#div_<?php Tab::tabIdEcho('listarAplicacaoInput'); ?>").remove();
                            $(data).appendTo("#<?php Tab::tabIdEcho('listarAplicacao'); ?>");
                        } else {
                            $("#div_<?php Tab::tabIdEcho('listarAplicacaoInput'); ?>").remove();
                            $(data).appendTo("#<?php Tab::tabIdEcho('listarAplicacao'); ?>");
                        }
                    }
                ) 
            }
        })
        
        $("#<?php Tab::tabIdEcho('btn_gravar'); ?>").click(function(){
            var nomeAplicacao = $("#<?php Tab::tabIdEcho('nomeAplicacao'); ?>").val();
            if (nomeAplicacao == "") {
                alert("O campo nome não pode ficar vazio");
                $("#<?php Tab::tabIdEcho('nomeAplicacao'); ?>").focus();
                return false;
            }
            $.post(
                "<?php echo BASE_URL . '/clinica/aplicacao/cadastrar'; ?>", 
                $("#<?php Tab::tabIdEcho('formAplicacao'); ?>").serialize(),
                function(data, status){
//                    alert(data);
                    if(status == 'success' && $.trim(data) != 'naopassou') {
                        alert("Aplicação registrada com sucesso!");
                    } else {
                        
                    }
                }
            )
        })
        
        $("#excluir_<?php Tab::tabIdEcho('listarAplicacaInput'); ?>").live("click", function() {
            var idAplicacao = $("#aplicacao_<?php Tab::tabIdEcho('listarAplicacaoInput'); ?>").attr('aplicacao');
            
            $.post(
                "<?php echo BASE_URL . '/clinica/aplicaca/excluir'; ?>", 
                {idAplicacao: idAplicacao},
                function(data, status){

                    if(status == 'success' && $.trim(data) != 'naopassou') {
                        $(this).parent().remove();
                        alert(data);
                    } else {
                        
                    }
                }
            )
        })
        
        $("#aplicacao_<?php Tab::tabIdEcho('listarAplicacaoInput'); ?>").live("click", function() {
            var idAplicacao = $(this).attr('aplicacao');
            $.post(
                "<?php echo BASE_URL . '/clinica/aplicacao/buscar'; ?>", 
                {idAplicacao: idAplicacao},
                function(data, status){
                    if(status == 'success' && $.trim(data) != 'naopassou') {
                        $(".<?php Tab::tabIdEcho('modulo'); ?>").attr("checked", false);
                        $("#<?php Tab::tabIdEcho('codAplicacao'); ?>").val(idAplicacao);
                        $("#<?php Tab::tabIdEcho('aplicacaoSubmit'); ?>").val("Editar");
                        $("#<?php Tab::tabIdEcho('nomeAplicacao'); ?>").val(data.nomeAplicacao);
                        
                        $.post(
                            "<?php echo BASE_URL . '/clinica/aplicacao/buscaraplicacaomodulo'; ?>", 
                            {idAplicacao: idAplicacao},
                            function(data, status){

                                if(status == 'success' && $.trim(data) != 'naopassou') {
                                    <?php $getId = Tab::getTabId('moduloAplicacao'); ?>
                                    for (i = 0; i < data.length; i++) {
                                        $("#<?php echo $getId; ?>_" + data[i].codModulo).attr("checked", true);
                                    }

                                } else {
                                    $(".<?php Tab::tabIdEcho('modulo'); ?>").attr("checked", false);
                                }
                            },
                            'json'
                        )
                    } else {
                        
                    }
                },
                'json'
            )
            
        })
        
        
    })
</script>

<style type="text/css">
    .listagem tr:hover {
        background:#b5dbf8;
        cursor: pointer;
    } 
</style>

<div id="<?php Tab::tabIdEcho('aplicacao_0_'); ?>">
    <table>
        <tr>
            <td class="ts">Aplicações Cadastrados</td>
            <td colspan="6" class="ts">Cadastro de Aplicações</td>
        </tr>
        <!-- LISTA -->
        <tr>
            <td class="tdLista" id="" width="300" style="vertical-align:top; ">
                <!-- Lista -->
                <table class="lista">
                    <tbody>
                        <tr>
                            <td style="vertical-align: top;">
                                <input type="text" class="pesquisa" name="pesquisa" id="<?php Tab::tabIdEcho('pesquisa'); ?>" />
                            </td>
                        </tr>
                        <tr>
                            <td style="vertical-align: top;">
                                <div id="<?php Tab::tabIdEcho('listarAplicacao'); ?>">
                                    <input type="hidden" id="<?php Tab::tabIdEcho('listarAplicacaoInput'); ?>" value="<?php Tab::tabIdEcho('listarAplicacaoInput'); ?>" />
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
            <td style="vertical-align: top;">
                <form id="<?php Tab::tabIdEcho('formAplicacao'); ?>" method="post" onsubmit="return false;" action="<?php echo $this->url(array("controller" => "aplicacao", "action" => "aplicacao")); ?>">
                    <input type="hidden" name="codAplicacao" id="<?php Tab::tabIdEcho('codAplicacao'); ?>" value="" />
                    <input type="hidden" name="aplicacaoSubmit" id="<?php Tab::tabIdEcho('aplicacaoSubmit'); ?>" value="" />
                    <table>
                        <tbody>
                            <tr>
                                <td class="tn">Nome:</td>
                                <td>
                                    <input class="i3" type="text" name="nomeAplicacao" id="<?php Tab::tabIdEcho('nomeAplicacao'); ?>" value="" />
                                </td>
                            </tr>
                            <tr>
                                <td class="tn" style="vertical-align: top;">Módulos:</td>
                                <td colspan="3">
                                    
                                    <?php
                                    $cont = 0;
                                    foreach ($modulos as $modulo) {
//                                            $display = ($cont % 2 != 0) ? "class='inline-block'" : "";
                                        $id = Tab::getTabId('moduloAplicacao');
                                        ?>
                                        <div class='inline-block'>
                                            <div class="inline-block" style="height: 20px;">
                                                <input type="checkbox" name="modulo[]" class="<?php Tab::tabIdEcho('modulo'); ?>"
                                                    id="<?php echo $id . "_" . $modulo->codModulo; ?>"
                                                    value="<?php echo $modulo->codModulo; ?>" />
                                            </div>
                                            <div class="inline-block"><?php echo $modulo->nomeModulo; ?></div>
                                        </div>
                                        <?php
                                        $cont++;
                                    }
                                    ?>
                                    
                                </td>
                            </tr>

                            <!-- Botão do formulário -->
                            <tr>
                                <td colspan="4" style="text-align: right; padding-top: 20px;">
                                    <div class="btn_c">
                                        <div class="btn_e">
                                            <div class="btn_d" onmouseover="" onmouseout="" id="<?php Tab::tabIdEcho('btn_gravar'); ?>">
                                                Gravar
                                            </div>      
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </form>
            </td>
        </tr>
    </table>
</div>