<?php
$usuario = Zend_Auth::getInstance()->getIdentity();
$aplicacoes = $this->aplicacoes;
?>
<link type="text/css" href="<?php echo dirname($_SERVER['PHP_SELF']); ?>/css/cadastros.css" rel="stylesheet" rev="stylesheet"/>

<script type="text/javascript">
    $(document).ready(function() {
        $("input, select, textarea").attr("autocomplete", "off");
        
        $('#<?php Tab::tabIdEcho('pesquisa'); ?>').focus();
        
        $("#<?php Tab::tabIdEcho('pesquisa'); ?>").keyup(function(){
            var palavra = $(this).val();
            var input = $("#<?php Tab::tabIdEcho('listarPerfilInput'); ?>").val();
            
            if (palavra.length > 2) {
                $.post(
                    "<?php echo BASE_URL . '/clinica/perfil/listar'; ?>", 
                    {perfil: palavra, input: input},
                    function(data, status){
                        if(status == 'success' && $.trim(data) != 'naopassou') {
                            $("#div_<?php Tab::tabIdEcho('listarPerfilInput'); ?>").remove();
                            $(data).appendTo("#<?php Tab::tabIdEcho('listarPerfil'); ?>");
                        } else {
                            $("#div_<?php Tab::tabIdEcho('listarPerfilInput'); ?>").remove();
                            $(data).appendTo("#<?php Tab::tabIdEcho('listarPerfil'); ?>");
                        }
                    }
                ) 
            }
        })
        
        $("#<?php Tab::tabIdEcho('btn_gravar'); ?>").click(function(){
            var nomePerfil = $("#<?php Tab::tabIdEcho('nomePerfil'); ?>").val();
            if (nomePerfil == "") {
                alert("O campo nome não pode ficar vazio");
                $("#<?php Tab::tabIdEcho('nomePerfil'); ?>").focus();
                return false;
            }
            $.post(
                "<?php echo BASE_URL . '/clinica/perfil/cadastrar'; ?>", 
                $("#<?php Tab::tabIdEcho('formPerfil'); ?>").serialize(),
                function(data, status){
//                    alert(data);
                    if(status == 'success' && $.trim(data) != 'naopassou') {
                        alert("Perfil alterado com sucesso!");
                    } else {
                        alert("Ocorreu um erro ao alterar/cadastrar o perfil, favor tente novamente.");
                    }
                }
            )
        })
        
        $("#excluir_<?php Tab::tabIdEcho('listarPerfilInput'); ?>").live("click", function() {
            var idPerfil = $("#perfil_<?php Tab::tabIdEcho('listarPerfilInput'); ?>").attr('perfil');
            
            $.post(
                "<?php echo BASE_URL . '/clinica/perfil/excluir'; ?>", 
                {idPerfil: idPerfil},
                function(data, status){
                    if(status == 'success' && $.trim(data) != 'naopassou') {
                                                
                    } else {
                        
                    }
                }
            )
        })
        
        $("#perfil_<?php Tab::tabIdEcho('listarPerfilInput'); ?>").live("click", function() {
            var idPerfil = $(this).attr('perfil');
            $.post(
                "<?php echo BASE_URL . '/clinica/perfil/buscar'; ?>", 
                {idPerfil: idPerfil},
                function(data, status){
                    
                    if(status == 'success' && $.trim(data) != 'naopassou') {
                        $(".<?php Tab::tabIdEcho('aplicacaoModuloAcao'); ?>").attr("checked", false);
                        $("#<?php Tab::tabIdEcho('codPerfil'); ?>").val(idPerfil);
                        $("#<?php Tab::tabIdEcho('perfilSubmit'); ?>").val("Editar");
                        $("#<?php Tab::tabIdEcho('nomePerfil'); ?>").val(data.nomePerfil);
                        
                        $.post(
                            "<?php echo BASE_URL . '/clinica/perfil/buscaraplicacaomoduloacao'; ?>", 
                            {idPerfil: idPerfil},
                            function(data, status){

                                if(status == 'success' && $.trim(data) != 'naopassou') {
                                    <?php $getId = Tab::getTabId('aplicacaoModuloAcao'); ?>
                                    for (i = 0; i < data.length; i++) {
                                        $("#<?php echo $getId; ?>_" + data[i].codAplicacao + data[i].codModulo + data[i].codAcao).attr("checked", true);
                                    }

                                } else {
                                    $(".<?php Tab::tabIdEcho('aplicacaoModuloAcao'); ?>").attr("checked", false);
                                }
                            },
                            'json'
                        )
                    } else {
                        
                    }
                },
                'json'
            )
            
        })
        
        
    })
</script>

<style type="text/css">
    .listagem tr:hover {
        background:#b5dbf8;
        cursor: pointer;
    } 
    
    
    
</style>

<div id="<?php Tab::tabIdEcho('perfil_0_'); ?>">
    <table>
        <tr>
            <td class="ts">Perfis Cadastrados</td>
            <td colspan="6" class="ts">Cadastro de Perfis</td>
        </tr>
        <!-- LISTA -->
        <tr>
            <td class="tdLista" id="" width="300" style="vertical-align:top; ">
                <!-- Lista -->
                <table class="lista">
                    <tbody>
                        <tr>
                            <td style="vertical-align: top;">
                                <input type="text" class="pesquisa" name="pesquisa" id="<?php Tab::tabIdEcho('pesquisa'); ?>" />
                            </td>
                        </tr>
                        <tr>
                            <td style="vertical-align: top;">
                                <div id="<?php Tab::tabIdEcho('listarPerfil'); ?>">
                                    <input type="hidden" id="<?php Tab::tabIdEcho('listarPerfilInput'); ?>" value="<?php Tab::tabIdEcho('listarPerfilInput'); ?>" />
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
            <td style="vertical-align: top;">
                <form id="<?php Tab::tabIdEcho('formPerfil'); ?>" method="post" onsubmit="return false;" action="<?php echo $this->url(array("controller" => "perfil", "action" => "perfil")); ?>">
                    <input type="hidden" name="codPerfil" id="<?php Tab::tabIdEcho('codPerfil'); ?>" value="" />
                    <input type="hidden" name="perfilSubmit" id="<?php Tab::tabIdEcho('perfilSubmit'); ?>" value="" />
                    <table>
                        <tbody>
                            
                            <tr>
                                <td class="tn">Nome:</td>
                                <td>
                                    <input class="i3" type="text" name="nomePerfil" id="<?php Tab::tabIdEcho('nomePerfil'); ?>" value="" />
                                </td>
                            </tr>
                            <tr>
                                <td class="tn" style="vertical-align: top;">Aplicação/Módulo/Ação:</td>
                                <td>
                                    <table>
                                        <?php
                                        foreach ($aplicacoes as $aplicacao) {
                                            ?>
                                            <tr>
                                                <td>
                                                    <strong><em><?php echo $aplicacao->nomeAplicacao; ?>:</em></strong>
                                                </td>
                                            </tr>
                                            <?php
                                            $modulos = Modulo::listarPorAplicacao($aplicacao->codAplicacao);
                                            foreach ($modulos as $modulo) {
                                                ?>
                                                <tr>
                                                    <td style="padding: 5px 0 5px 15px;">
                                                        <strong><?php echo $modulo->nomeModulo; ?>:</strong>
                                                    </td>
                                                </tr>
                                                
                                                    <?php
                                                    $acoes = Acao::buscarPorModulo($modulo->codModulo);
                                                    foreach ($acoes as $acao) {
                                                        $id = Tab::getTabId('aplicacaoModuloAcao');
                                                        ?>

                                                            <tr>
                                                    <td style="padding-left: 30px;">
                                                        <div class='inline-block' style="margin-top: -5px;">
                                                            <div class="inline-block" style="height: 17px;">
                                                                <input type="checkbox" name="permissao[<?php echo $aplicacao->codAplicacao; ?>][<?php echo $modulo->codModulo; ?>][<?php echo $acao->codAcao; ?>]" 
                                                                        class="<?php Tab::tabIdEcho('aplicacaoModuloAcao'); ?>"
                                                                        id="<?php echo $id . "_" . $aplicacao->codAplicacao . $modulo->codModulo . $acao->codAcao; ?>"
                                                                        value="<?php echo $acao->codAcao; ?>" />
                                                            </div>
                                                            <div class="inline-block"><?php echo $acao->nomeAcao; ?></div>
                                                        </div>
                                                    </td>
                                                </tr>        
                                                        
                                                        <?php
                                                    }
                                                ?>
                                                    
                                                <?php
                                            }
                                        }
                                        ?>
                                    </table>
                                </td>
                            </tr>

                            <!-- Botão do formulário -->
                            <tr>
                                <td colspan="4" style="text-align: right; ">
                                    <div class="btn_c">
                                        <div class="btn_e">
                                            <div class="btn_d" onmouseover="" onmouseout="" id="<?php Tab::tabIdEcho('btn_gravar'); ?>">
                                                Gravar
                                            </div>      
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            
                        </tbody>
                    </table>
                </form>
            </td>
        </tr>
    </table>
</div>