<link type="text/css" rel="stylesheet" rev="stylesheet" href="<?php echo dirname($_SERVER['PHP_SELF']); ?>/css/gehos.css" />
<link type="text/css" rel="stylesheet" rev="stylesheet" href="<?php echo dirname($_SERVER['PHP_SELF']); ?>/css/cadastros.css" />
<link type="text/css" rel="stylesheet" rev="stylesheet" href="<?php echo dirname($_SERVER['PHP_SELF']); ?>/css/login.css" />

<script type="text/javascript">
    $(document).ready(function() {

    });
    
    function submitenter(myfield,e){
        var keycode;
        if (window.event){
            keycode = window.event.keyCode;
        }else if (e) {
            keycode = e.which;
        }else{
            return true;
        }
        
        if (keycode == 13){
            myfield.form.submit();
            document.getElementById("formLogin").submit();
//            document.getElementById('popup_principal1').className='popshow1';
//            document.getElementById("webmail").reset();
            return false;
        }else{
            return true;
        }
    }
</script>

<div>
    <img id="logo" width="200" height="75" src="<?php echo dirname($_SERVER['PHP_SELF']); ?>/img/LOGO FINAL.png" />
    <div id="loginForm">
        <div id="loginInfo">
            <br /><br />
            Para acessar o sistema, informe suas credenciais e tecle Enter.
        </div>
        <form id="formLogin" action="<?php echo $this->url(array("controller" => "index", "action" => "login"));?>" 
              method="post" name="login" onsubmit="return false;">
<!--            <input type="hidden" name="sal" id="inputSal" value="<?php
//                $sal = rand();
//                $session->sal = $sal;
//                echo $sal;
?>" />-->
            <center>
                <table border="0" cellpadding="0" cellspacing="10">
                    <tbody>
                        <tr>
                            <td>Usu&aacute;rio:</td>
                            <td>
                                <input type="text" name="user" id="inputUser" value="" />
                            </td>
                        </tr>
                        <tr>
                            <td>Senha:</td>
                            <td><input type="password" name="pass" id="inputPass" value="" onkeyup="return submitenter(this,event)" /></td>
                        </tr>
                        <tr>
                            <td colspan ="2" align="right"> <a style="font-weight:normal; font-size:8pt; text-decoration:none"  href="esqueciSenha.php">Esqueci minha senha</a></td>
                        </tr>	
                    </tbody>
                </table>
            </center>
        </form>

    </div>
    <div id="sombra">
    </div>
</div>